apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: shaikmustafa/dm
        ports:
        - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80           # Port inside the cluster
      targetPort: 80     # Port on the container
      nodePort: 30080    # External port on the node (range: 30000–32767)



